#!/usr/bin/env php
<?php

use Izzy\System\Database\DatabaseMigrationManager;

// EZMoonblow core file.
require dirname(__DIR__, 2).'/lib/common.php';

try {
	$migrationName = DatabaseMigrationManager::promptMigrationName();
	$file = DatabaseMigrationManager::createMigration($migrationName);
	echo "Created migration: $file\n";
} catch (Exception $e) {
	echo "Error: ".$e->getMessage()."\n";
	die(-1);
}
