#!/bin/bash

# Get project’s root directory.
IZZY_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

cd "$IZZY_ROOT"

docker image prune -f
docker compose build --no-cache --pull
docker image prune -f
